version: '3.6'
services:
  mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: businesses
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db-init/sql:/docker-entrypoint-initdb.d/
      -  mysql-data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      -  redis-vol:/data

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-vol:/data/db
      - ./db-init/mongo:/docker-entrypoint-initdb.d/
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daniel
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=yelpAPI
    ports:
      - 27017:27017
volumes:
  mongodb-vol:
    name: mongo-vol
  redis-vol:
      name: redis-vol
  mysql-data:
    name: businesses-mysql-data

# docker-compose -f dev-compose.yml up