# Use root/example as user/password credentials
version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb:/data/db
      - ./db-init/mongo:/docker-entrypoint-initdb.d/
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=daniel
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=breweryAPI
    ports:
      - 27017:27017
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  api:
    build: .
    restart: always
    container_name: "brewery"
    environment:
      MONGO_HOST: mongodb
      MONGO_DATABASE: breweryAPI
      MONGO_USER: breweryUser
      MONGO_PASSWORD: breweryPassword
    depends_on:
      - mongodb
    ports:
      - 3000:3000
volumes:
  mongodb:
  esdata1: